apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-text-app 
  labels:
    app: my-text-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: my-text-app
  template:
    metadata:
      labels:
        app: my-text-app 
    spec:
      containers:
      - name: my-text-app 
        image: prakie7/textimize-react-app:latest-textm 
        ports:
        - containerPort: 3000 
