apiVersion: v1
kind: Service
metadata:
  name: my-text-app
spec:
  type: LoadBalancer
  selector:
    app: my-text-app
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
status:
  loadBalancer: {}
